repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      -   id: check-ast
      -   id: check-byte-order-marker
      -   id: check-case-conflict
      -   id: check-json
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: mixed-line-ending
      -   id: debug-statements
      -   id: pretty-format-json
          args:
            - "--autofix"
            - "--no-ensure-ascii"

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: flake8-with-plugins
        name: flake8 with custom plugins
        entry: flake8
        language: system
        types: [python]
        exclude: scripts/lint/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests~=2.32.0
          - pandas-stubs~=2.2.2
          - sqlalchemy[mypy]==2.0.39
          - tabulate==0.9.0
